---
- name: deploy a namenode for a HDFS cluster
  hosts: 'namenode'
  
  roles:
    - common
    - hosts-file
    - role: hadoop-common
      vars_files: 
        - playbook/roles/hosts-file/vars/main.yml